spring:
  application:
    name: CommercialApp
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  datasource:
    url: jdbc:postgresql://localhost:5432/commercial
    username: postgres
    password: postgres
  sql:
    init:
      platform: postgres
      mode: always
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/commercialApp
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
server:
  port: 8090


jwt:
  auth:
    converter:
      resource-id: commercial-rest-api
      principle-attribute: preferred_username
